### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by kamalmarhubi** [foxsy/tfvolattid#1]
This has been a handy tool for a couple of migrations. I'd like to adapt your code for a larger migration, but I'm not sure how it's licensed. https://choosealicense.com/ is a handy place to help figure out which license you'd like to use.

Thanks for putting this up!

**Comment by foxsy** [comment]
I'm glad this helped out!  Hopefully there will be a pull request shortly for Terraform that will check to see if the volume is already attached to the correct instance/device and just rewrite it to the state file instead of spewing errors.  I added a license file to the repository.
